// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQTQ-eAQwE81FS9QLWBK98AnFf-dprm64',
    appId: '1:1003157322056:web:6a2d9e5a5846cfda329b7d',
    messagingSenderId: '1003157322056',
    projectId: 'voice-banking-3078d',
    authDomain: 'voice-banking-3078d.firebaseapp.com',
    storageBucket: 'voice-banking-3078d.firebasestorage.app',
    measurementId: 'G-9C09Z8FXG0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJY7mC2ZBaQT91pewSijgPTknl2BVaOJw',
    appId: '1:1003157322056:android:c0392bfe80b41d16329b7d',
    messagingSenderId: '1003157322056',
    projectId: 'voice-banking-3078d',
    storageBucket: 'voice-banking-3078d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4LzunuME0xt2CojR0usp8gO3YrV812bE',
    appId: '1:1003157322056:ios:fdbd810813581ef7329b7d',
    messagingSenderId: '1003157322056',
    projectId: 'voice-banking-3078d',
    storageBucket: 'voice-banking-3078d.firebasestorage.app',
    iosBundleId: 'com.example.bankKltt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4LzunuME0xt2CojR0usp8gO3YrV812bE',
    appId: '1:1003157322056:ios:fdbd810813581ef7329b7d',
    messagingSenderId: '1003157322056',
    projectId: 'voice-banking-3078d',
    storageBucket: 'voice-banking-3078d.firebasestorage.app',
    iosBundleId: 'com.example.bankKltt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQTQ-eAQwE81FS9QLWBK98AnFf-dprm64',
    appId: '1:1003157322056:web:0bcb43f0eeb4c890329b7d',
    messagingSenderId: '1003157322056',
    projectId: 'voice-banking-3078d',
    authDomain: 'voice-banking-3078d.firebaseapp.com',
    storageBucket: 'voice-banking-3078d.firebasestorage.app',
    measurementId: 'G-6FE9ZF3VY4',
  );

}